name: cis194-homework
version: 0.1.0.0
github: "GabrielMajeri/hello-stack"
license: MIT
author: "Gabriel Majeri"
maintainer: "gabriel.majeri6@gmail.com"
copyright: "2019 Gabriel Majeri"

extra-source-files: README.md

dependencies: base >= 4.7 && < 5

library:
  source-dirs: src

tests:
  cis194-homework-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies: cis194-homework
