# Resolver to choose a 'specific' stackage snapshot or a compiler version.
resolver: lts-15.7

# User packages to be built.
packages:
  - .

# Control whether we use the GHC we find on the path
system-ghc: true

# Allow a newer minor version of GHC than the snapshot specifies
compiler-check: newer-minor
