name: Haskell CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Cache stack files
      uses: actions/cache@v1
      with:
        path: ~/.stack/
        key: stack-${{ hashFiles('*.yaml') }}

    - name: Run tests
      run: stack test
